apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - replicas.yaml
  - flow-generator.yaml
configMapGenerator:
  - name: ibg-hybrid-runtime-profiles
    namespace: ibg-hybrid-testbed
    files:
      - runtime-profiles.json
  - name: ibg-hybrid-planning-links
    namespace: ibg-hybrid-testbed
    files:
      - controller-inputs.json
generatorOptions:
  disableNameSuffixHash: true

