apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibg-hybrid-controller
  namespace: ibg-hybrid-testbed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibg-hybrid-replica-discovery
  namespace: ibg-hybrid-testbed
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibg-hybrid-controller-discovers-replicas
  namespace: ibg-hybrid-testbed
subjects:
  - kind: ServiceAccount
    name: ibg-hybrid-controller
    namespace: ibg-hybrid-testbed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibg-hybrid-replica-discovery

