apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - replicas.yaml
  - flow-generator.yaml
configMapGenerator:
  - name: replica-profiles
    namespace: ibg-testbed
    files:
      - profiles.json
generatorOptions:
  disableNameSuffixHash: true
